server:
  port: 8080

spring:
  application:
    name: instrument-explore
  datasource:
    url: jdbc:mysql://localhost:3306/guzheng_experience_rebuild?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      schema-locations: classpath:db/schema.sql
      mode: always

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.guzheng.explore.entity,com.guzheng.explore.dto
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.guzheng.explore.mapper: debug
